#!/usr/bin/env python3

# Copyright (c) 2015-2020 Clearmatics Technologies Ltd
# Copyright (c) 2021-2021 Zkrypto Inc.
# Author: H. Oh
#
# SPDX-License-Identifier: LGPL-3.0+

from zeth.cli.constants import \
    PROVER_SERVER_ENDPOINT_DEFAULT, PROVER_CONFIGURATION_FILE_DEFAULT, \
    INSTANCE_FILE_DEFAULT, ZKLAY_SECRET_ADDRESS_FILE_DEFAULT, ZKLAY_AUDIT_SECRET_ADDRESS_FILE_DEFAULT, WALLET_DIR_DEFAULT, \
    ETH_NETWORK_FILE_DEFAULT, ETH_NETWORK_DEFAULT
from zeth.cli.utils import ClientConfig
from zeth.cli.zeth_deploy import deploy
from zeth.cli.zklay_gen_address import gen_address
from zeth.cli.zklay_audit_key_gen import audit_key_gen
from zeth.cli.zklay_deposit import deposit
from zeth.cli.zeth_sync import sync
from zeth.cli.zeth_mix import mix
from zeth.cli.zeth_ls_notes import ls_notes
from zeth.cli.zeth_ls_commits import ls_commits
from zeth.cli.zeth_sync import sync
from click import group, command, option, pass_context, ClickException, Context
from click_default_group import DefaultGroup  # type: ignore
from typing import Optional, Any


@command()
@pass_context
def help(ctx: Context) -> None:
    """
    Print help and exit
    """
    # Note, this command is implemented to ensure that an error is raised if no
    # subcommand is specified (which also catches errors in scripts).
    print(ctx.parent.get_help())  # type: ignore
    raise ClickException("no command specified")


@group(cls=DefaultGroup, default_if_no_args=True, default="help")
@option(
    "--eth-network",
    default=None,
    help="Ethereum RPC endpoint, network or config file "
    f"(default: '{ETH_NETWORK_FILE_DEFAULT}' if it exists, otherwise "
    f"'{ETH_NETWORK_DEFAULT}')")
@option(
    "--prover-server",
    default=PROVER_SERVER_ENDPOINT_DEFAULT,
    help=f"Prover server endpoint (default={PROVER_SERVER_ENDPOINT_DEFAULT})")
@option(
    "--prover-config-file",
    default=PROVER_CONFIGURATION_FILE_DEFAULT,
    help=f"Prover config file (default={PROVER_CONFIGURATION_FILE_DEFAULT})")
@option(
    "--instance-file",
    default=INSTANCE_FILE_DEFAULT,
    help=f"Instance file (default={INSTANCE_FILE_DEFAULT})")
@option(
    "--address-file",
    default=ZKLAY_SECRET_ADDRESS_FILE_DEFAULT,
    help=f"Zklay zecret address file (default={ZKLAY_SECRET_ADDRESS_FILE_DEFAULT})")
@option(
    "--audit-address-file",
    default=ZKLAY_AUDIT_SECRET_ADDRESS_FILE_DEFAULT,
    help=f"Zklay auditor zecret address file (default={ZKLAY_AUDIT_SECRET_ADDRESS_FILE_DEFAULT})")
@option(
    "--wallet-dir",
    default=WALLET_DIR_DEFAULT,
    help=f"Wallet directory (default={WALLET_DIR_DEFAULT})")
@pass_context
def zklay(
        ctx: Context,
        eth_network: Optional[str],
        prover_server: str,
        prover_config_file: str,
        instance_file: str,
        address_file: str,
        audit_address_file: str,
        wallet_dir: str) -> None:
    if ctx.invoked_subcommand == "help":
        ctx.invoke(help)
    ctx.ensure_object(dict)
    ctx.obj = ClientConfig(
        eth_network=eth_network,
        prover_server_endpoint=prover_server,
        prover_config_file=prover_config_file,
        instance_file=instance_file,
        address_file=address_file,
        audit_address_file=audit_address_file,
        wallet_dir=wallet_dir)


zklay.add_command(deploy)
zklay.add_command(gen_address)
zklay.add_command(audit_key_gen)
zklay.add_command(deposit)
zklay.add_command(sync)
zklay.add_command(mix)
zklay.add_command(ls_notes)
zklay.add_command(ls_commits)
zklay.add_command(help)


if __name__ == "__main__":
    zklay()  # pylint: disable=no-value-for-parameter
